version: "2"
services:
  es:
    image: elasticsearch:5.6-alpine
    container_name: es
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./config/es.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/es:/usr/share/elasticsearch/data/:rw
      - ./plugins/pinyin:/usr/share/elasticsearch/plugins/pinyin:ro
    networks:
      - net-es
    stdin:
      -true
  es1:
    image: elasticsearch:5.6-alpine
    container_name: es1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
      - ./config/es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./plugins/pinyin:/usr/share/elasticsearch/plugins/pinyin:ro
    networks:
      - net-es
  es2:
    image: elasticsearch:5.6-alpine
    container_name: es2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9202:9200"
      - "9302:9300"
    volumes:
      - ./config/es2.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./plugins/pinyin:/usr/share/elasticsearch/plugins/pinyin:ro  
    networks:
      - net-es
  es3:
    image: elasticsearch:5.6-alpine
    container_name: es3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9203:9200"
      - "9303:9300"
    volumes:
      - ./config/es3.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./plugins/pinyin:/usr/share/elasticsearch/plugins/pinyin:ro
    networks:
      - net-es
  kibana:
    image: kibana
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://es2:9200
    depends_on:
     - es
    ports:
      - 5601:5601
    networks:
      - net-es
networks:
  net-es:
