version: '3.1'

services:
  zoo1:
    image: jacklin/zookeeper:3.7.0
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 8080:8080
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181 server.4=zoo4:2888:3888;2181
      JAVA_HOME: /usr/local/openjdk-11
      ZOO_DATA_DIR: /zookeeper/zoo1/data
      ZOO_DATA_LOG_DIR: /zookeeper/zoo1/datalog
      JVMFLAGS: "-Xmx1024m"
    volumes:
      - vdb-zoo1-data:/zookeeper/zoo1/data:rw
      - vdb-zoo1-datalog:/zookeeper/zoo1/datalog:rw
  zoo2:
    image: jacklin/zookeeper:3.7.0
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181 server.4=zoo4:2888:3888;2181
      JAVA_HOME: /usr/local/openjdk-11
      ZOO_DATA_DIR: /zookeeper/zoo2/data
      ZOO_DATA_LOG_DIR: /zookeeper/zoo2/datalog
      JVMFLAGS: "-Xmx1024m"
    volumes:
      - vdb-zoo2-data:/zookeeper/zoo2/data:rw
      - vdb-zoo2-datalog:/zookeeper/zoo2/datalog:rw

  zoo3:
    image: jacklin/zookeeper:3.7.0
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181 server.4=zoo4:2888:3888;2181
      JAVA_HOME: /usr/local/openjdk-11
      ZOO_DATA_DIR: /zookeeper/zoo3/data
      ZOO_DATA_LOG_DIR: /zookeeper/zoo3/datalog
      JVMFLAGS: "-Xmx1024m"
    volumes:
      - vdb-zoo3-data:/zookeeper/zoo3/data:rw
      - vdb-zoo3-datalog:/zookeeper/zoo3/datalog:rw
  # zoo4:
  #   image: jacklin/zookeeper:3.7.0
  #   restart: always
  #   hostname: zoo4
  #   ports:
  #     - 2184:2181
  #   environment:
  #     ZOO_MY_ID: 4
  #     ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181 server.4=0.0.0.0:2888:3888;2181
  #     JAVA_HOME: /usr/local/openjdk-11
  #     ZOO_DATA_DIR: /zookeeper/zoo4/data
  #     ZOO_DATA_LOG_DIR: /zookeeper/zoo4/datalog
  #     JVMFLAGS: "-Xmx1024m"
  #   volumes:
  #     - vdb-zoo4-data:/zookeeper/zoo4/data:rw
  #     - vdb-zoo4-datalog:/zookeeper/zoo4/datalog:rw


volumes:
  vdb-zoo1-data:
    driver: local
  vdb-zoo1-datalog:
    driver: local
  vdb-zoo2-data:
    driver: local
  vdb-zoo2-datalog:
    driver: local
  vdb-zoo3-data:
    driver: local
  vdb-zoo3-datalog:
    driver: local
  # vdb-zoo4-data:
  #   driver: local
  # vdb-zoo4-datalog:
  #   driver: local
