version: "2.1"
services:
  flash-redis-n1:
    image: redislabs/redis
    volumes:
      - vdb-1:/var/opt
    ports:
     - 8443:8443
     - 11000-11002:12000-12002
    cap_add:
     - SYS_RESOURCE
    mem_limit: 2G
    memswap_limit: 4G
    networks:
      net-flash-redis:
        ipv4_address: 172.16.0.2
  flash-redis-n2:
    image: redislabs/redis
    volumes:
      - vdb-2:/var/opt
    ports:
     - 8444:8443
     - 12000-12002:12000-12002
    cap_add:
     - SYS_RESOURCE
    mem_limit: 2G
    memswap_limit: 4G
    networks:
      net-flash-redis:
        ipv4_address: 172.16.0.3
  flash-redis-n3:
    image: redislabs/redis
    volumes:
      - vdb-3:/var/opt
    ports:
     - 8445:8443
     - 13000-13002:12000-12002
    cap_add:
     - SYS_RESOURCE
    mem_limit: 2G
    memswap_limit: 4G
    networks:
      net-flash-redis:
        ipv4_address: 172.16.0.4
volumes:
  vdb-1:
    driver: local
  vdb-2:
    driver: local
  vdb-3:
    driver: local
networks:
  net-flash-redis:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.1