cluster.name: my-test
node.name: es3
node.master: false
node.data: true
node.ingest: true

path.data: /usr/share/elasticsearch/data

network.host: es3
http.port: 9200
transport.tcp.port: 9300
http.cors.enabled: true
http.cors.allow-origin: "*"

discovery.zen.ping.unicast.hosts: ["es:9300", "es1:9300", "es2:9300", "es3:9300"]
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping_timeout: 5s

bootstrap.memory_lock: true
action.destructive_requires_name: true
