version: '3.1'
services:
  
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "[R))T]{root}"
    volumes:
      - "/docker-compose/mysql8/data:/var/lib/mysql"
      - "/docker-compose/mysql8/conf/conf.d:/etc/mysql/conf.d"
      - "/data/:/data"
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080