version: "3.7"
services:
  pika-shard:
    image: jacklin/pika-kubernetes:latest
    restart: always
    hostname: pika-shard
    environment: 
      - "IS_DOUBLE_MODE=false"
      - "INSTANCE_MODE=sharding"
      - "DEFAULT_SLOT_NUM=16"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      # - "./conf/master-1.conf:/pika/conf/pika.conf"
      - "shard-0-vdb:/pika/data/"
    ports:
     - "9221"
    networks:
      - net-pika
networks:
  net-pika:
    external: true
volumes:
  shard-0-vdb:
    driver: local
