cluster.name: my-test
cluster.initial_master_nodes: ["es","es1"]

node.name: es5
node.master: false
node.data: true

network.host: es5

http.port: 9200
http.cors.enabled: true
http.cors.allow-origin: "*"

transport.port: 9300

discovery.seed_hosts: ["es1","es2","es3","es4","es"]

bootstrap.memory_lock: true
action.destructive_requires_name: true

xpack.security.enabled: true
