version: '3.0'
services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6.20
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - 5432:5432
    volumes:
      - vdb-pgsql:/var/lib/postgresql/data
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5
  kong-pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "jacklin@shouyiren.net"
      PGADMIN_DEFAULT_PASSWORD: "Game.7723"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
      - 5480:80
    networks:
      - kong-net
  #######################################
  # Kong database migration
  #######################################
  kong-migration:
      image: kong:latest
      command: "kong migrations bootstrap"
      networks:
        - kong-net
      restart: on-failure
      environment:
        KONG_DATABASE: postgres
        KONG_PG_HOST: kong-database
        KONG_PG_USER: kong #必须加上，不然连接数据库失败导致初始化会失败
        KONG_PG_PASSWORD: kong #必须加上，不然连接数据库失败导致初始化会失败
        KONG_CASSANDRA_CONTACT_POINTS: kong-database
      links:
        - kong-database
      depends_on:
        - kong-database
  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    restart: always
    networks:
      - kong-net
    links:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong #必须加上，不然连接数据库失败导致初始化会失败
      KONG_PG_PASSWORD: kong #必须加上，不然连接数据库失败导致初始化会失败
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong_kong_1:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
  kong2:
    image: kong:latest
    restart: always
    networks:
      - kong-net
    links:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong #必须加上，不然连接数据库失败导致初始化会失败
      KONG_PG_PASSWORD: kong #必须加上，不然连接数据库失败导致初始化会失败
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - 8800:8000
      - 8801:8001
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong_kong2_1:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
  #volumes:   若有配置文件要自己配置，则建议挂在出来
  #  - /opt/kong/kong.conf:/etc/kong/kong.conf
  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga_db"  #注意是用户名：密码@数据库服务名称：端口
    networks:
      - kong-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database
  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:latest
    #restart: always
    networks:
        - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_PASSWORD: kong #必须加上密码，不然会失败
      TOKEN_SECRET: km1GUr4RkcQD8DewhJPNXrCuZwcKmqjb
      DB_DATABASE: konga_db
      NODE_ENV: production
    depends_on:
      - kong-database
    ports:
      - "1337:1337"
  #######################################
  # prometheus
  #######################################
  prometheus:
    image: jacklin/prometheus:master
    networks:
        - kong-net
    ports:
        - "9090:9090"
  #######################################
  # grafana
  #######################################
  grafana:
    image: jacklin/grafana:master
    networks:
        - kong-net
    ports:
        - "3000:3000"
volumes:
  vdb-pgsql:
    driver: local
networks:
  kong-net:
    driver: bridge
